param(
  [string]$OutputDir = "dist",
  [string]$ChromePath = "",
  [string]$KeyPath = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$outputRoot = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $OutputDir))
$stageDir = Join-Path $outputRoot "webstore-package"

function Resolve-Chrome {
  param([string]$ExplicitPath)

  if ($ExplicitPath -and (Test-Path -LiteralPath $ExplicitPath)) {
    return [System.IO.Path]::GetFullPath($ExplicitPath)
  }

  $candidates = @(
    "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
    "$env:ProgramFiles(x86)\Google\Chrome\Application\chrome.exe",
    "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
  )

  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      return [System.IO.Path]::GetFullPath($candidate)
    }
  }

  throw "Chrome executable not found. Pass -ChromePath explicitly."
}

& (Join-Path $PSScriptRoot "build-webstore.ps1") -OutputDir $OutputDir

$manifest = Get-Content -Path (Join-Path $repoRoot "manifest.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$version = $manifest.version
$chrome = Resolve-Chrome $ChromePath
$tempProfile = Join-Path ([System.IO.Path]::GetTempPath()) "aily-log-export-pack-$PID"
$args = @(
  "--user-data-dir=$tempProfile",
  "--no-first-run",
  "--no-default-browser-check",
  "--pack-extension=$stageDir"
)

if ($KeyPath) {
  if (-not (Test-Path -LiteralPath $KeyPath)) {
    throw "CRX key file not found: $KeyPath"
  }
  $args += "--pack-extension-key=$([System.IO.Path]::GetFullPath($KeyPath))"
}

Write-Host "Chrome Web Store uploads use the ZIP generated by build-webstore.ps1."
Write-Host "Generating optional CRX for local testing..."
$generatedCrx = "$stageDir.crx"
$generatedPem = "$stageDir.pem"
$targetCrx = Join-Path $outputRoot "aily-runtime-log-exporter-v$version.crx"
$targetPem = Join-Path $outputRoot "aily-runtime-log-exporter.pem"

foreach ($path in @($generatedCrx, $generatedPem, $targetCrx)) {
  if (Test-Path -LiteralPath $path) {
    Remove-Item -LiteralPath $path -Force
  }
}

try {
  Start-Process -FilePath $chrome -ArgumentList $args -Wait -WindowStyle Hidden

  for ($i = 0; $i -lt 20 -and -not (Test-Path -LiteralPath $generatedCrx); $i++) {
    Start-Sleep -Milliseconds 250
  }

  if (-not (Test-Path -LiteralPath $generatedCrx)) {
    throw "Chrome did not produce CRX output: $generatedCrx"
  }

  Move-Item -LiteralPath $generatedCrx -Destination $targetCrx -Force
  Write-Host "CRX package: $targetCrx"

  if (Test-Path -LiteralPath $generatedPem) {
    Move-Item -LiteralPath $generatedPem -Destination $targetPem -Force
    Write-Host "Private key generated: $targetPem"
    Write-Host "Keep this PEM private and do not commit it."
  }
} finally {
  $tempFull = [System.IO.Path]::GetFullPath($tempProfile)
  $tempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
  if ($tempFull.StartsWith($tempRoot, [System.StringComparison]::OrdinalIgnoreCase) -and (Test-Path -LiteralPath $tempFull)) {
    Remove-Item -LiteralPath $tempFull -Recurse -Force -ErrorAction SilentlyContinue
  }
}
